name: camera_2fps_app
description: App Flutter per registrazione video time-lapse a 2 FPS con creazione video nativa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  video_editor: ^1.5.0       # For video creation from images

  gallery_saver: ^2.3.2

  # Camera access
  camera: ^0.10.5+5
  
  # File paths
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true